name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # This overrides the default shallow clone - we need the full history because
          # the tests access prior commits.
          # https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
          fetch-depth: 0
          # We need the git2go submodule
          submodules: recursive
      - uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: build git2go
        run: cd git2go && make install-static
      - name: get dependencies
        run: go get -v -t -d ./...
      - name: compile git2go
        run: cd $(go env GOPATH)/src/github.com/libgit2/git2go && git submodule update --init && make install-static
      - name: test race
        run: go test -v -race ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.0
